### ISSUE TITLE
Why can't I set WaveView opaque？

### ISSUE THREAD

**Issue by nantofu** [gelitenight/WaveView#5]
I want to set WaveView opaque.
I have set up the Alpha of wavePaint1 to 255.
But no matter what i do, View is still transparent.
Do you have some good method?

Like this(the red view should be opaque).
![image](https://cloud.githubusercontent.com/assets/8243147/10708550/6bc5f506-7a3f-11e5-8e75-393d3ef393f7.png)

**Comment by gelitenight** [comment]
It's a bug which can be fixed by adding:
```
wavePaint.setStrokeWidth(2);
```

The fix is included in latest commit.

**Comment by nantofu** [comment]
Thanks,I have found the method.
But I want to know why the **Stroke Width** can influence the alpha of drawable？

**Comment by gelitenight** [comment]
@nantofu I'm confused with that too. 
It seems to be a bug with Android 4.x and below, because the code without Stroke Width set worked well with my phone running Android 5.0 and Android 6.0
